language: node_js
node_js:
- '8'
env:
  global:
    - SAUCE_USERNAME=jstockwin1
    - KEYSTONE_PREBUILD_ADMIN=true
  matrix:
    - JOB=lint-and-test-cov
matrix:
  include:
    - node_js: '8'
      script:
        - travis_retry npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group006Fields
    - node_js: '8'
      script:
        - travis_retry npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group005Item
    - node_js: '8'
      script:
        - travis_retry npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group004List
    - node_js: '8'
      script:
        - travis_retry npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group003Home
    - node_js: '8'
      script:
        - travis_retry npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group002App
    - node_js: '8'
      script:
        - travis_retry npm run test-e2e-saucelabs-group
      env:
        - JOB=e2e GROUP=group001Login
    - node_js: '8'
      script:
        - npm run test-admin
      env:
        - JOB=admin_tests_node_8
    - node_js: '8'
      script:
        - npm run test-unit
      env:
        - JOB=unit_tests_node_8


before_script:
- sleep 15
script:
- npm run lint
- npm run test-cov
sudo: required
notifications:
  email:
  - github@unaussprechlich.net
services:
- mongodb
git:
  depth: 10
cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
